services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
    - $DATA/postgres:/var/lib/postgresql/data
    networks:
    - storage

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    networks:
    - storage

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: on-failure
    environment:
    - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT}
    volumes:
    - $DATA/mariadb:/var/lib/mysql:rw
    networks:
    - storage


networks:
  storage:
    name: storage
