services: 
  borg:
    container_name: borg
    image: pschiffe/borg
    volumes:
    - /mnt/borg:/borg/repo
    - $DATA/borg/config:/root
    - $DATA:/borg/data/docker-data:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
    - BORG_REPO=/borg/repo
    - BORG_PASSPHRASE=${BORG_PASSPHRASE}
    - BACKUP_DIRS=/borg/data
    - COMPRESSION=lz4
    - PRUNE=1
    restart: "no"
    profiles:
    - dnr

