services:
  gitea-runner:
    container_name: gitea-runner
    image: gitea/act_runner:latest
    restart: unless-stopped
    environment:
    - GITEA_INSTANCE_URL=https://git.bhasher.com
    - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_TOKEN}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

