singleuser:
  defaultUrl: "/lab"
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    EDITOR: "vim"
  memory:
    limit: 1G
    guarantee: 100M
  cpu:
    limit: 1.
    guarantee: 1.
  storage:
    dynamic:
      storageClass: longhorn
    capacity: 2Gi

hub:
  extraEnv:
    OAUTH_TLS_VERIFY: "0"
    OAUTH2_TLS_VERIFY: "0"
  config:
    Authenticator:
      admin_users:
        - bhasher
    GenericOAuthenticator:
      client_id: jupyterhub
      client_secret: 8sbWBuDMmKIvcjfTQTg12f2ycRV3Y3Cy
      oauth_callback_url: https://jupyter.bhasher.com/hub/oauth_callback
      authorize_url: https://openid.bhasher.com/realms/external/protocol/openid-connect/auth
      token_url: https://openid.bhasher.com/realms/external/protocol/openid-connect/token
      userdata_url: https://openid.bhasher.com/realms/external/protocol/openid-connect/userinfo
      login_service: OpenID
      username_key: preferred_username
      userdata_params:
        state: state
    JupyterHub:
      authenticator_class: generic-oauth

ingress:
  enabled: true
  hosts:
    - jupyter.bhasher.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "bhasherca-k3s-issuer"
    cert-manager.io/common-name: "jupyter.bhasher.com"
  tls:
  - hosts:
    - jupyter.bhasher.com
    secretName: jupyterhub-tls

prePuller:
  continuous:
    enabled: false
