version: '3.7'
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    volumes:
      - /mnt/nfs/jellyfin:/config
      - /mnt/movies/series:/data/tvshows
      - /mnt/movies/movies:/data/movies
      - /mnt/movies/musics:/data/musics
    environment:
      - TZ=Europe/Paris
    networks:
    - external
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints: [node.labels.HWA == true]
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.bhasher.com`)"
      - "traefik.http.routers.jellyfin.entrypoints=internalsecure,externalsecure"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=http"

networks:
  external:
    external: true
