version: '3.7'
services:
  pihole:
    image: cbcrowe/pihole-unbound:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
    ports:
    - mode: host
      protocol: tcp
      published: 53
      target: 53
    - mode: host
      protocol: udp
      published: 53
      target: 53
    - mode: host
      protocol: tcp
      published: 80
      target: 80
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: 'z9w1r0FvKKvuLdXIygDlhidUhinERhOKZTBJtOXCMaFLi1dZvh0f2vsy9miDqsFu'
      WEBTHEME: 'default-dark'
      REV_SERVER: 'false'
      PIHOLE_DNS_: '127.0.0.1#5335'
      DNSSEC: 'true'
      DNSMASQ_LISTENING: 'all'
      FTLCONF_REPLY_ADDR4: '192.168.1.220'
      FTLCONF_RATE_LIMIT: '0/0'
      FTL_CMD: 'debug'
    volumes:
    - '/mnt/nfs/pihole/config:/etc/pihole'
    - '/mnt/nfs/pihole/dnsmasq.d:/etc/dnsmasq.d'    
    # - '/tmp/config:/etc/pihole'
    # - '/tmp/dnsmasq.d:/etc/dnsmasq.d'    
