services:
  whoami:
    container_name: whoami
    image: containous/whoami:v1.5.0
    restart: on-failure:3
    environment:
    - TZ=Europe/Paris
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.whoami.rule=Host(`whoami.bhasher.com`)"
    - "traefik.http.services.whoami.loadbalancer.server.port=80"
    - "traefik.http.routers.whoami.tls=true"
    - "traefik.http.routers.whoami.tls.certresolver=http"
    - "traefik.http.routers.whoami.entrypoints=internalsecure"
    - "traefik.http.routers.whoami.middlewares=sablier1h@docker"
    networks:
    - external

networks:
  external:
    external: true
