services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: unless-stopped
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
    - $DATA/postgres:/var/lib/postgresql/data
    networks:
    - storage

  valkey:
    container_name: valkey
    image: valkey/valkey:alpine
    restart: unless-stopped
    networks:
    - storage

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    environment:
    - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT}
    volumes:
    - $DATA/mariadb:/var/lib/mysql:rw
    networks:
    - storage


networks:
  storage:
    name: storage
