services: 
  borgmatic:
    container_name: borgmatic
    image: ghcr.io/borgmatic-collective/borgmatic:latest
    restart: unless-stopped
    volumes:
    - $DATA:/mnt/source:ro
    - $BACKUP:/mnt/borg-repository:rw
    - $CONFIG/borgmatic/etc:/etc/borgmatic.d
    - $DATA/borgmatic/borg:/root/.config/borg
    - $DATA/borgmatic/ssh:/root/.ssh
    - $DATA/borgmatic/cache:/root/.cache/borg
    - /etc/localtime:/etc/localtime:ro
    environment:
    - TZ=Europe/Paris
    - BORG_PASSPHRASE=none
    - BACKUP_CRON=0 5 * * *
    - RUN_ON_STARTUP=true
    networks:
    - storage

