services:
  fail2ban:
    container_name: fail2ban
    restart: unless-stopped
    image: crazymax/fail2ban:latest
    environment: 
    - TZ=Europe/Paris
    - PUID=1000
    - PGID=1000
    - F2B_DB_PURGE_AGE=30d
    volumes:
    - $DATA/fail2ban:/data
    - $DATA/vaultwarden:/remotelogs/vaultwarden:ro
    # authelia
    # hass
    # traefik ?
