services:
  plausible_events_db:
    container_name: plausible_clickhouse
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - $DATA/plausible/clickhouse/data:/var/lib/clickhouse
      - $DATA/plausible/clickhouse/logs:/var/log/clickhouse-server
      - $CONFIG/plausible/clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      - $CONFIG/plausible/clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
      - $CONFIG/plausible/clickhouse/low-resources.xml:/etc/clickhouse-server/config.d/low-resources.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m
    networks:
      - plausible

  plausible:
    container_name: plausible_plausible
    image: ghcr.io/plausible/community-edition:v2.1.4
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_events_db:
        condition: service_healthy
    volumes:
      - $DATA/plausible/plausible/data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - TMPDIR=/var/lib/plausible/tmp
      - BASE_URL=https://plausible.bhasher.com
      - SECRET_KEY_BASE=${PLAUSIBLE_SK}
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/plausible
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.plausible.rule=Host(`plausible.bhasher.com`)"
    - "traefik.http.services.plausible.loadbalancer.server.port=8000"
    - "traefik.http.routers.plausible.tls=true"
    - "traefik.http.routers.plausible.tls.certresolver=http"
    - "traefik.http.routers.plausible.entrypoints=internalsecure,externalsecure"
    - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - external
      - storage
      - plausible

networks:
  plausible:
