services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1
    restart: unless-stopped
    environment:
    - USER_UID=1000
    - USER_GID=1000
    - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
    - GITEA__mailer__PASSWD=${SMTP_PASSWORD} 
    volumes:
    - $DATA/gitea:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    depends_on:
    - postgres
    - redis
    ports:
    - 2222:22/tcp
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.gitea.rule=Host(`git.bhasher.com`)"
    - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    - "traefik.http.routers.gitea.tls=true"
    - "traefik.http.routers.gitea.tls.certresolver=http"
    - "traefik.http.routers.gitea.entrypoints=internalsecure,externalsecure"
    networks:
    - gitea
    - external
    - storage

  gitea-runner:
    container_name: gitea-runner
    image: gitea/act_runner:latest
    restart: unless-stopped
    environment:
    - GITEA_INSTANCE_URL=https://git.bhasher.com
    - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_TOKEN}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - "com.centurylinklabs.watchtower.enable=true"
    networks:
    - gitea


networks:
  gitea:
