services: 
  onlyoffice-documentserver:
    container_name: onlyoffice-documentserver
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    environment:
    - JWT_SECRET=${ONLYOFFICE_JWT}
    - WOPI_ENABLED=true
    - JWT_ENABLED=true
    volumes:
    - $DATA/onlyoffice/DocumentServer/logs:/var/log/onlyoffice 
    - $DATA/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data
    - $DATA/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice
    - $DATA/onlyoffice/DocumentServer/db:/var/lib/postgresql
    - $DATA/onlyoffice/DocumentServer/rabbitmq:/var/lib/rabbitmq
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.onlyoffice-editor.rule=Host(`onlyoffice-editor.bhasher.com`)"
    - "traefik.http.services.onlyoffice-editor.loadbalancer.server.port=80"
    - "traefik.http.routers.onlyoffice-editor.tls=true"
    - "traefik.http.routers.onlyoffice-editor.tls.certresolver=http"
    - "traefik.http.routers.onlyoffice-editor.entrypoints=internalsecure,externalsecure"
    - "traefik.http.routers.onlyoffice-editor.middlewares=httpsupgrade"
    networks:
    - external
    - file

  seafile-storage:
    container_name: seafile-storage
    image: mariadb:10.11
    environment:
    - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT}
    volumes:
    - $DATA/file/db:/var/lib/mysql
    networks:
    - file

  seafile-memcached:
    container_name: seafile-memcached
    image: memcached:1.6.18
    entrypoint: memcached -m 256
    networks:
    - file

  seafile:
    container_name: seafile
    image: seafileltd/seafile-mc:latest
    volumes:
    - $DATA/file/data:/shared   
    environment:
    - DB_HOST=seafile-storage
    - DB_ROOT_PASSWD=${MARIADB_ROOT}
    - TIME_ZONE=Europe/Paris
    - SEAFILE_ADMIN_EMAIL=seafile.lan@bhasher.com
    - SEAFILE_ADMIN_PASSWORD=${SEAFILE_PASSWORD}
    - SEAFILE_SERVER_LETSENCRYPT=false
    - SEAFILE_SERVER_HOSTNAME=file.bhasher.com
    - DEBUG=true
    depends_on:
    - seafile-storage
    - seafile-memcached
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.seafile.rule=Host(`file.bhasher.com`)"
    - "traefik.http.services.seafile.loadbalancer.server.port=80"
    - "traefik.http.routers.seafile.tls=true"
    - "traefik.http.routers.seafile.tls.certresolver=http"
    - "traefik.http.routers.seafile.entrypoints=internalsecure"
    networks:
    - file
    - external

networks:
  file:
  external:
    external: true
