services:
  invoiceplane:
    container_name: invoiceplane
    image: mhzawadi/invoiceplane:latest
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - $DATA/invoiceplane/uploads:/var/www/html/uploads
    - type: bind
      source: $DATA/invoiceplane/ipconfig.php
      target: /var/www/html/ipconfig.php
    environment:
    - TZ=Europe/Paris
    - IP_URL=https://invoice.bhasher.com
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.invoice.rule=Host(`invoice.bhasher.com`)"
    - "traefik.http.services.invoice.loadbalancer.server.port=80"
    - "traefik.http.routers.invoice.tls=true"
    - "traefik.http.routers.invoice.tls.certresolver=http"
    - "traefik.http.routers.invoice.entrypoints=internalsecure,externalsecure"
    - "com.centurylinklabs.watchtower.enable=true"
    networks:
    - external
    - invoice

  invoiceplane-db:
    container_name: invoiceplane-db
    image: mariadb:10.4.10
    volumes:
      - $DATA/invoiceplane/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT}
      - MYSQL_DATABASE=invoiceplane
      - MYSQL_USER=invoiceplane
      - MYSQL_PASSWORD=${MARIADB_ROOT}
    networks:
    - invoice

networks:
  invoice:
