services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    volumes:
      - $DATA/mediaserver/jellyfin2:/config
      - /mnt/movies/series:/media/tvshows
      - /mnt/movies/movies:/media/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.bhasher.com`)"
      - "traefik.http.routers.jellyfin.entrypoints=internalsecure,externalsecure"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=http"
      - "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Media"
      - "homepage.weight=100"
      - "homepage.name=Jellyfin"
      - "homepage.icon=jellyfin.svg"
      - "homepage.href=https://jellyfin.bhasher.com"
      - "homepage.description=Media Server"
      - "homepage.widget.type=jellyfin"
      - "homepage.widget.key=${JELLYFIN_API_KEY}"
      - "homepage.widget.url=http://jellyfin:8096"
      - 'homepage.widget.fields=["movies","series"]'
      - "homepage.widget.enableBlocks=true"
      - "homepage.widget.enableNowPlaying=true"
      - "homepage.widget.enableUser=true"
      - "homepage.widget.showEpisodeNumber=true"
    networks:
      - auth
      - external

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    volumes:
      - $DATA/mediaserver/radarr:/config
      - /mnt/movies/movies:/movies
      - /mnt/movies/tmp:/downloads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.bhasher.com`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=http"
      - "traefik.http.routers.radarr.entrypoints=internalsecure"
      - "traefik.http.routers.radarr.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Media"
      - "homepage.weight=101"
      - "homepage.name=Radarr"
      - "homepage.icon=radarr.svg"
      - "homepage.href=https://radarr.bhasher.com"
      - "homepage.description=Movies Management"
      - "homepage.widget.type=radarr"
      - "homepage.widget.key=${RADARR_API_KEY}"
      - "homepage.widget.url=http://radarr:7878"
      - "homepage.widget.enableQueue=true"
      - 'homepage.widget.fields=["wanted","queued","missing"]'
    networks:
      - mediaserver
      - external

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - $DATA/mediaserver/sonarr:/config
      - /mnt/movies/series:/tv
      - /mnt/movies/tmp:/downloads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.bhasher.com`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=http"
      - "traefik.http.routers.sonarr.entrypoints=internalsecure"
      - "traefik.http.routers.sonarr.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Media"
      - "homepage.weight=102"
      - "homepage.name=Sonarr"
      - "homepage.icon=sonarr.svg"
      - "homepage.href=https://sonarr.bhasher.com"
      - "homepage.description=Shows Management"
      - "homepage.widget.type=sonarr"
      - "homepage.widget.key=${SONARR_API_KEY}"
      - "homepage.widget.url=http://sonarr:8989"
      - "homepage.widget.enableQueue=true"
      - 'homepage.widget.fields=["wanted","series","queued"]'
    networks:
      - mediaserver
      - external

  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - $DATA/mediaserver/transmission:/config
      - /mnt/movies/tmp:/downloads
      - /mnt/movies/torrents:/watch
    ports:
      - 51413:51413/tcp
      - 51413:51413/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.bhasher.com`)"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - "traefik.http.routers.transmission.tls=true"
      - "traefik.http.routers.transmission.tls.certresolver=http"
      - "traefik.http.routers.transmission.entrypoints=internalsecure"
      - "traefik.http.routers.transmission.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Media"
      - "homepage.weight=103"
      - "homepage.name=Transmission"
      - "homepage.icon=transmission.svg"
      - "homepage.href=https://transmission.bhasher.com"
      - "homepage.description=Torrents Manager"
      - "homepage.widget.type=transmission"
      - "homepage.widget.url=http://transmission:9091"
      - 'homepage.widget.fields=["leech","seed","download","upload"]'
    networks:
      - mediaserver
      - external

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - $DATA/mediaserver/prowlarr:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.bhasher.com`)"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.tls.certresolver=http"
      - "traefik.http.routers.prowlarr.entrypoints=internalsecure"
      - "traefik.http.routers.prowlarr.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Media Server"
      - "homepage.name=Prowlarr"
      - "homepage.icon=prowlarr.svg"
      - "homepage.href=https://prowlarr.bhasher.com"
      - "homepage.description=Torrent Provider Management"
    networks:
      - mediaserver
      - external

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Paris
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - mediaserver

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    volumes:
      - $DATA/mediaserver/bazarr:/config
      - /mnt/movies/movies:/movies
      - /mnt/movies/series:/tv
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.bhasher.com`)"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.routers.bazarr.tls.certresolver=http"
      - "traefik.http.routers.bazarr.entrypoints=internalsecure"
      - "traefik.http.routers.bazarr.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Media Server"
      - "homepage.name=Bazarr"
      - "homepage.icon=bazarr.svg"
      - "homepage.href=https://bazarr.bhasher.com"
      - "homepage.description=Subtitle Management"
    networks:
      - mediaserver
      - external

networks:
  mediaserver:
