services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1
    environment:
    - USER_UID=1000
    - USER_GID=1000
    - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
    - GITEA__mailer__PASSWD=${SMTP_PASSWORD} 
    restart: unless-stopped
    volumes:
    - $DATA/gitea:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    depends_on:
    - postgres
    - redis
    ports:
    - 2222:22/tcp
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.gitea.rule=Host(`git.bhasher.com`)"
    - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    - "traefik.http.routers.gitea.tls=true"
    - "traefik.http.routers.gitea.tls.certresolver=http"
    - "traefik.http.routers.gitea.entrypoints=internalsecure"
    networks:
    - external
    - storage

networks:
  external:
    external: true
  storage:
    external: true
