services:
  owntracks_recorder:
    container_name: owntracks_recorder
    image: owntracks/recorder
    environment:
    - OTR_PORT=0
    - OTR_HTTPHOST=0.0.0.0
    volumes:
    - $DATA/owntracks/store:/store
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.owntracks-recorder.rule=Host(`owntracks.bhasher.com`)"
    - "traefik.http.routers.owntracks-recorder.entrypoints=internalsecure"
    - "traefik.http.services.owntracks-recorder.loadbalancer.server.port=8083"
    - "traefik.http.routers.owntracks-recorder.tls=true"
    - "traefik.http.routers.owntracks-recorder.tls.certresolver=http"
    #- "traefik.http.routers.owntracks-recorder.middlewares=authelia@docker"
    - "com.centurylinklabs.watchtower.enable=true"
    networks:
    - external

networks:
  external:
    external: true
