services:
  app:
    container_name: monica
    image: monica
    environment:
    - APP_KEY=${MONICA_APPKEY}
    - DB_HOST=mariadb
    - DB_USERNAME=root
    - DB_PASSWORD=${MARIADB_ROOT}
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.monica.rule=Host(`monica.bhasher.com`)"
    - "traefik.http.services.monica.loadbalancer.server.port=80"
    - "traefik.http.routers.monica.tls=true"
    - "traefik.http.routers.monica.tls.certresolver=http"
    - "traefik.http.routers.monica.entrypoints=internalsecure"
    volumes:
      - $DATA/monica:/var/www/html/storage
    restart: unless-stopped
    networks:
    - storage
    - external

networks:
  external:
    external: true
  storage:
    external: true
