services:
  wikijs:
    container_name: wikijs
    image: ghcr.io/requarks/wiki:2
    restart: unless-stopped
    depends_on:
    - postgres
    environment:
    - DB_TYPE=postgres
    - DB_HOST=postgres
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_PASS=${POSTGRES_PASSWORD}
    - DB_NAME=wikijs
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.wikijs.rule=Host(`wiki.bhasher.com`)"
    - "traefik.http.routers.wikijs.entrypoints=internalsecure"
    - "traefik.http.services.wikijs.loadbalancer.server.port=3000"
    - "traefik.http.routers.wikijs.tls=true"
    - "traefik.http.routers.wikijs.tls.certresolver=http"
    - "com.centurylinklabs.watchtower.enable=true"
    networks:
    - storage
    - external

