services:
  invoiceplane:
    container_name: invoiceplane
    image: mhzawadi/invoiceplane:latest
    volumes:
    - $DATA/invoiceplane/uploads:/var/www/html/uploads
    - $DATA/invoiceplane/ipconfig.php:/var/www/html/ipconfig.php
    - /etc/localtime:/etc/localtime:ro
    command: sh -c "apk add php7-mbstring php7-iconv php7-json gd && nginx -g 'daemon off;'"
    environment:
    - IP_URL=https://invoice.bhasher.com
    #- MYSQL_HOST=mariadb
    #- MYSQL_USER=root
    #- MYSQL_PASSWORD=${MARIADB_ROOT}
    #- MYSQL_DB=InvoicePlane
    #- DISABLE_SETUP=false
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.invoice.rule=Host(`invoice.bhasher.com`)"
    - "traefik.http.services.invoice.loadbalancer.server.port=80"
    - "traefik.http.routers.invoice.tls=true"
    - "traefik.http.routers.invoice.tls.certresolver=http"
    - "traefik.http.routers.invoice.entrypoints=internalsecure,externalsecure"
    networks:
    - external
    - storage

networks:
  invoice:
  external:
    external: true
  storage:
    external: true
