services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Paris
    - MAX_WORKERS=1
    - WEB_CONCURRENCY=1
    - BASE_URL=https://recipes.bhasher.com
    - OIDC_AUTH_ENABLED=true
    - OIDC_SIGNUP_ENABLE=true
    - OIDC_REMEMBER_ME=true
    - OIDC_AUTO_REDIRECT=true
    - OIDC_CONFIGURATION_URL=https://idp.bhasher.com/.well-known/openid-configuration
    - OIDC_CLIENT_ID=mealie
    - OIDC_PROVIDER_NAME=Authelia
    - OIDC_USER_GROUP=everybody
    - OIDC_ADMIN_GROUP=admin
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.mealie.rule=Host(`recipes.bhasher.com`)"
    - "traefik.http.services.mealie.loadbalancer.server.port=9000"
    - "traefik.http.routers.mealie.tls=true"
    - "traefik.http.routers.mealie.tls.certresolver=http"
    - "traefik.http.routers.mealie.entrypoints=internalsecure,externalsecure"
    - "com.centurylinklabs.watchtower.enable=true"
    volumes:
    - $DATA/mealiev1/:/app/data
    networks:
    - external

networks:
  external:
    external: true
