services: 
  syncthing:
    container_name: syncthing
    image: syncthing/syncthing:latest
    hostname: snode0
    environment:
    - PUID=33
    - PGID=33
    volumes:
    - $DATA/syncthing:/var/syncthing:rw
    - /mnt/syncDocuments:/mnt/SyncDocuments:rw
    - /mnt/brieuc:/mnt/brieuc:rw
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.syncthing.rule=Host(`syncthing.bhasher.com`)"
    - "traefik.http.routers.syncthing.entrypoints=internalsecure"
    - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
    - "traefik.http.routers.syncthing.tls=true"
    - "traefik.http.routers.syncthing.tls.certresolver=http"
    - "traefik.http.routers.syncthing.middlewares=authelia@docker"
    - "com.centurylinklabs.watchtower.enable=true"
    ports:
    - 22000:22000/tcp # TCP file transfers
    - 22000:22000/udp # QUIC file transfers
    - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    networks:
    - external

networks:
  external:
    external: true
