services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    volumes:
      - $DATA/ollama:/root/.ollama
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.ollama.rule=Host(`ollama.bhasher.com`)"
    - "traefik.http.services.ollama.loadbalancer.server.port=11434"
    - "traefik.http.routers.ollama.tls=true"
    - "traefik.http.routers.ollama.tls.certresolver=http"
    - "traefik.http.routers.ollama.entrypoints=internalsecure"
    #- "traefik.http.routers.ollama.middlewares=authelia@docker"
    networks:
    - external
