services:
  opentripplanner:
    container_name: opentripplanner
    image: docker.io/opentripplanner/opentripplanner:2.5.0
    command: --load --serve
    restart: unless-stopped
    volumes:
    #- type: bind
    #  source: $DATA/opentripplanner/graph.obj
    #  target: /var/opentripplanner/graph.obj
    #- type: bind
    #  source: $CONFIG/otp/otp-config.json
    #  target: /var/opentripplanner/otp-config.json,readonly
    #- type: bind
    #  source: $CONFIG/otp/router-config.json
    #  target: /var/opentripplanner/router-config.json,readonly
    - $DATA/opentripplanner/graph.obj:/var/opentripplanner/graph.obj
    - $CONFIG/otp:/var/opentripplanner

    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.otp.rule=Host(`maps.bhasher.com`)"
    - "traefik.http.routers.otp.entrypoints=internalsecure"
    - "traefik.http.services.otp.loadbalancer.server.port=8080"
    - "traefik.http.routers.otp.tls=true"
    - "traefik.http.routers.otp.tls.certresolver=http"
    - "traefik.http.routers.otp.middlewares=authelia@docker"
    - "com.centurylinklabs.watchtower.enable=true"
    networks:
    - external

networks:
  external:
    external: true
