services:
  blog:
    container_name: blog
    image: git.bhasher.com/bhasher/blog:latest
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.blog.rule=Host(`blog.bhasher.com`)"
    - "traefik.http.routers.blog.entrypoints=internalsecure"
    - "traefik.http.services.blog.loadbalancer.server.port=80"
    - "traefik.http.routers.blog.tls=true"
    - "traefik.http.routers.blog.tls.certresolver=http"
    - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      start_period: 20s
      start_interval: 5s
      timeout: 10s
      retries: 3
    networks:
    - external
