services:
  dmarc:
    container_name: dmarc
    image: gutmensch/dmarc-report:latest
    environment:
      - TZ=Europe/Paris
      - REPORT_DB_TYPE=pgsql
      - REPORT_DB_HOST=postgres
      - REPORT_DB_PORT=5432
      - REPORT_DB_NAME=dmarc
      - REPORT_DB_USER=postgres
      - REPORT_DB_PASS=${POSTGRES_PASSWORD}
      - PARSER_IMAP_SERVER=imap.bhasher.com
      - PARSER_IMAP_PORT=993
      - PARSER_IMAP_USER=${SMTP_USER}
      - PARSER_IMAP_PASS=${SMTP_PASSWORD}
      - PARSER_IMAP_READ_FOLDER=reports.dmarc.inbox
      - PARSER_IMAP_MOVE_FOLDER=reports.dmarc.processed
      - PARSER_IMAP_MOVE_FOLDER_ERR=reports.dmarc.error
      - PARSER_IMAP_SSL=1
      - PARSER_IMAP_TLS=0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dmarc.rule=Host(`dmarc.bhasher.com`)"
      - "traefik.http.routers.dmarc.entrypoints=internalsecure"
      - "traefik.http.services.dmarc.loadbalancer.server.port=80"
      - "traefik.http.routers.dmarc.tls=true"
      - "traefik.http.routers.dmarc.tls.certresolver=http"
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - postgres
    networks:
      - external
      - storage
