services:
  opentripplanner:
    container_name: opentripplanner
    image: docker.io/opentripplanner/opentripplanner:2.8.0_2025-05-22T13-21
    command: --load --serve
    restart: unless-stopped
    volumes:
      - $DATA/opentripplanner:/var/opentripplanner

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.otp.rule=Host(`maps.bhasher.com`)"
      - "traefik.http.routers.otp.entrypoints=internalsecure"
      - "traefik.http.services.otp.loadbalancer.server.port=8080"
      - "traefik.http.routers.otp.tls=true"
      - "traefik.http.routers.otp.tls.certresolver=http"
      #- "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Management"
      - "homepage.name=OpenTripPlanner"
      - "homepage.icon=openstreetmap.webp"
      - "homepage.href=https://maps.bhasher.com"
      - "homepage.description=Routing Server"
    networks:
      - external

networks:
  external:
    external: true
