services:
  wireguard:
    container_name: wireguard
    image: lscr.io/linuxserver/wireguard:latest
    restart: always
    volumes:
    - $DATA/wireguard:/config
    - /lib/modules:/lib/modules
    ports:
    - 51821:51820/udp
    environment:
    - TZ=Europe/Paris
    - SERVERURL=vpn.bhasher.com
    - SERVERPORT=51821
    - PEERS=5
    - PEERDNS=auto
    - INTERNAL_SUBNET=10.13.14.0
    - ALLOWEDIPS=0.0.0.0/0
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
    sysctls:
    - net.ipv4.conf.all.src_valid_mark=1
