apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: devops
  name: sealed-secret
spec:
  project: k3pi

  source:
    repoURL: https://git.bhasher.com/Bhasher/K3Pi.git
    targetRevision: HEAD
    path: services/utils/sealed-secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
    
  syncPolicy:
    automated:
      prune: true