apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: devops
  name: wireguard
spec:
  project: k3pi

  source:
    repoURL: https://git.bhasher.com/Bhasher/K3Pi.git
    targetRevision: HEAD
    path: services/apps/wireguard/

  destination:
    server: https://kubernetes.default.svc
    namespace: wireguard

  syncPolicy:
    automated:
      prune: true