kind: Service
apiVersion: v1
metadata:
 name: bazarr
 namespace: external-endpoints
spec:
 type: ClusterIP
 ports:
 - port: 6767
   targetPort: 6767

---

kind: Endpoints
apiVersion: v1
metadata:
 name: bazarr
 namespace: external-endpoints
subsets:
 - addresses:
     - ip: 192.168.1.201
   ports:
     - port: 6767

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr
  namespace: external-endpoints
  annotations:
    cert-manager.io/cluster-issuer: "bhasherca-k3s-issuer"
    cert-manager.io/common-name: "bazarr.bhasher.com"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - bazarr.bhasher.com
    secretName: bazarr-tls
  rules:
  - host: bazarr.bhasher.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bazarr
            port:
              number: 6767