kind: Service
apiVersion: v1
metadata:
 name: docker
 namespace: external-endpoints
spec:
 type: ClusterIP
 ports:
 - port: 5000

---

kind: Endpoints
apiVersion: v1
metadata:
 name: docker
 namespace: external-endpoints
subsets:
 - addresses:
     - ip: 192.168.1.201
   ports:
     - port: 5000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker
  namespace: external-endpoints
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    cert-manager.io/cluster-issuer: "bhasherca-k3s-issuer"
    cert-manager.io/common-name: "docker.bhasher.com"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - docker.bhasher.com
    secretName: docker-tls
  rules:
  - host: docker.bhasher.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: docker
            port:
              number: 5000