kind: Service
apiVersion: v1
metadata:
 name: sonarr
 namespace: external-endpoints
spec:
 type: ClusterIP
 ports:
 - port: 8989
   targetPort: 8989

---

kind: Endpoints
apiVersion: v1
metadata:
 name: sonarr
 namespace: external-endpoints
subsets:
 - addresses:
     - ip: 192.168.1.201
   ports:
     - port: 8989

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  namespace: external-endpoints
  annotations:
    cert-manager.io/cluster-issuer: "bhasherca-k3s-issuer"
    cert-manager.io/common-name: "sonarr.bhasher.com"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - sonarr.bhasher.com
    secretName: sonarr-tls
  rules:
  - host: sonarr.bhasher.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 8989