apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie
  namespace: cloud
data:
  DB_ENGINE: postgres
  POSTGRES_USER: mealie
  POSTGRES_SERVER: postgres.storage.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: mealie
  DEFAULT_GROUP: Home
  BASE_URL: https://cook.bhasher.com
  # LDAP_AUTH_ENABLED: true
  # LDAP_SERVER_URL: ldap.idp.svc.cluster.local
  # LDAP_BIND_TEMPLATE: uid={},ou=users,dc=bhasher,dc=com
  # LDAP_ADMIN_FILTER: memberOf=cn=admin,ou=groups,dc=bhasher,dc=com
  