apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: storage
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA/ATIev78mJwjXhu/qIiSblsIMWATQ1HwEAZtko/c+IXDa9Jp/oLeBkWF97ljcCZLiJpeTrYvbmG1bT1o5DTSAUP+P316AvtQHTimx2NjzWWdThFhh0tcLrW3ymBjWv2fJjEgLsoKay0fMG3LtM/hb/cYSy1wk9qLhpFAymsD8gOREyzQKA8imMsXi7gBFZbD0CQE88b9OBH51jGkXZLtZif3jnTRZvMagGqp2DvVLJD7ogmU3eR2DyZqCiR2AX7Uyhtk25hggHnFzc2YJjiRXQRvwX77/HLo0vhSiUTzpWabfBtX1AKBC+IkvsikXtLZVDWhp9SLmIVcCp7PfseqBkefCN5vkU35nMN1FG+BukTl7Dv6kYqYIBaxLek6IFziSAzusAFPlntfJmlTneCIfcIulqGNb3MpImw5QPhIuEhT9dGuKqBYWSG9vURh/wwkLQ19eetkz/yGX87v+4k5OcemdjVQNIuyk3nKdxf+9M/CAQUjCbmj8UQNpmxuvL/f/ORlcqfMV0qpwoN8ia2GPtclXlWIb0VWHtNZpKm09zdn2O/qOm9x/t/N0yJiO+3rqpiCBI7DasP8KdmrNngDKUydvxwZEB5FNTqM+N+C3DmS6zLnXkhCHz6uSNj3S9B5NCGP4C3L0AVmErBm66kcj947lKl9JHjCLhgMeNclxnEe2Wicxf5Kp0lPcDkno/iCaXO95G09Vqv4DPBE39DYSrmjyVa5XOxG0Y5C3EKUR2gzYnVE1UkJCvsHb8IR5bdFZCIU9ZvjEc0ltOguPvNcC
    REPLICATION_PASSWORD: AgBveuPsVVRP6z2M6PYjasSSHXIsRIa4OlSSFjgQ/ZqM8EW02YxVn5pzfSsuJHpXU67s1mvQn+l5SAcCHyd3Myx9u8FmI9cISyoGb1e4sYwW3Am5xyIjcYsSGVhg1jKaMc40ZlFCMM1+5TJ7arTzKiNMnKqeoGVVt6ePAfhCiufP0qkHjt/ro6Jba/lj6iAqIcZGtX+MgmqXrRtXOzt7RDqzt2Pp+UuI1y0bFaQYtZT/d48rpj6bsvxnlpLq4S6Y9sYoFTe0VRSHBuN+sf9OKUcfGi9JTJlGNpf4e7Hbdcd00OXZ6izArfQCV5aWL5rw0EC3REzOw/owzfMWUBB2GkMDaqem1kt4jxWBKnhax1YFb8gn0RuIptnxb18aG8nZBqqSD/KgRL3VGh3TNLe5tPfgmCgyMJGFPrPCuyUdIuh1QKUhT+xQ52/9dCLRsXhZlPuToZiV1s5uZK1nx4O0wKFSJu3N0VDkT03EcLh4WJj7PTcyaCB78IsqdHOkrbz/Cs2BjMuH/h0u9+zUnpg84wglRlrfO7dQjJoYVdBmFJWWLwEp6+GUyn352hVi3CHzaewpXFwoHoUwFIdzfoimvWzC9daqC5qw6ARFIk8SGdq4xUKHkbJfkh/Qj3sqR4/GwrhfSgD9gXPfD7ynzxZVkeEjTm7YYGQr841qtARTt/IRRTWEymbHwGuaZ1aa7Gzjjn55MjJ623O80P0o4nBjmwGRswjWExPlHKEyja3dvmR1R3fsrqWOcLiDmoBTwuZldE1yJ2DEeWpnin14JGYvggBw
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: storage

