http:
  routers:
    truenas:
      rule: "Host(`truenas.bhasher.com`)"
      service: truenas
      tls: 
        certresolver: http
      entrypoints: internalsecure

    mikrotik:
      rule: "Host(`router.bhasher.com`)"
      service: mikrotik
      tls: 
        certresolver: http
      entrypoints: internalsecure

  services:
    truenas:
      loadBalancer:
        servers:
        - url: http://192.168.1.201
    mikrotik:
      loadBalancer:
        servers:
        - url: http://192.168.1.1:8080
