pageInfo:
  title: Service Desk
  description: Welcome to service-desk dashboard!
  navLinks:
    - title: HomeLab
      path: https://hub.bhasher.com
      target: sametab
appConfig:
  theme: adventure
  layout: auto
  iconSize: small
  language: en
  statusCheck: true
  colCount: 4
sections:
  - name: Public services
    icon: fa-server
    displayData:
      sortBy: most-used
      rows: 1
      cols: 2
      collapsed: false
      hideForGuests: false
    items:
      - title: '4040'
        description: Compte global (activation, reset, ...)
        url: https://uclouvain.be/4040
        statusCheck: false
        id: 0_1507_
      - title: 8282 - SD
        description: Catalogue de services / ivanti
        url: https://uclouvain.be/8282
        statusCheck: false
        id: 1_1507_sd
      - title: Wifi (public)
        icon: ''
        url: https://uclouvain.be/fr/decouvrir/wifi.html
        statusCheck: false
        id: 2_1507_wifipublic
      - title: Wifi (intra)
        url: >-
          https://intranet.uclouvain.be/fr/myucl/services-informatiques/wifi-en-cas-de-problemes.html
        statusCheck: false
        id: 3_1507_wifiintra
      - title: Permanances WiFi
        icon: ''
        statusCheck: false
        id: 4_1507_permananceswifi
  - name: Private services
    displayData:
      sortBy: default
      rows: 1
      cols: 2
      collapsed: false
      hideForGuests: false
    items:
      - title: LDAP
        url: https://sites.uclouvain.be/sisu/tools/ldapsearch/LDAPsearchSISU.php
        statusCheck: false
        id: 0_1631_ldap
      - title: Ivanti
        icon: ''
        url: >-
          https://servicedesk.uclouvain.be/ServiceDesk.WebAccess/wd/query/list.rails?class_name=IncidentManagement.Incident&query=_IncidentsouvertsFirstetSD
        statusCheck: false
        id: 1_1631_ivanti
      - title: Confluence
        url: https://uclouvain.atlassian.net/wiki/spaces/SD/overview
        statusCheck: false
        id: 2_1631_confluence
      - title: MS Console
        url: http://msconsole.siws.ucl.ac.be/
        statusCheck: false
        id: 3_1631_msconsole
