appConfig:
  theme: adventure
  layout: auto
  iconSize: small
  language: en
  statusCheck: true
  colCount: 4
pageInfo:
  title: Service Desk
  description: Welcome to service-desk dashboard!
  navLinks:
    - title: HomeLab
      path: https://hub.bhasher.com
      target: sametab
  footerText: ''
sections:
  - name: Public services
    icon: fa-server
    displayData:
      sortBy: most-used
      rows: 1
      cols: 2
      collapsed: false
      hideForGuests: false
    items:
      - title: '4040'
        description: Compte global (activation, reset, ...)
        url: https://uclouvain.be/4040
        statusCheck: false
        id: 0_1507_
      - title: 8282 - Services
        description: Catalogue de services / ivanti
        url: https://uclouvain.be/8282
        statusCheck: false
        id: 1_1507_services
      - title: Wifi (public)
        icon: ''
        url: >-
          https://uclouvain.atlassian.net/wiki/spaces/CDSMEXTP/pages/293798036/Permanences+WiFi+et+MFA+pour+les+tudiants#%C3%80-Louvain-La-Neuve
        id: 2_1507_wifipublic
      - title: Wifi (intra)
        url: >-
          https://intranet.uclouvain.be/fr/myucl/services-informatiques/wifi-en-cas-de-problemes.html
        statusCheck: false
        id: 3_1507_wifiintra
      - title: Permanances WiFi
        icon: ''
        url: >-
          https://intranet.uclouvain.be/fr/myucl/services-informatiques/wifi-permanence.html
        statusCheck: false
        id: 4_1507_permananceswifi
      - title: ADE infos
        url: https://uclouvain.be/fr/facultes/sc/comment-fonctionne-ade.html
        statusCheck: false
        id: 5_1507_adeinfos
      - title: Doc (public)
        url: >-
          https://uclouvain.atlassian.net/wiki/spaces/CDSMEXTP/pages/1003749410/Logiciels+libres
        id: 6_1507_docpublic
  - name: Private services
    displayData:
      sortBy: default
      rows: 1
      cols: 2
      collapsed: false
      hideForGuests: false
    items:
      - title: LDAP
        url: https://sites.uclouvain.be/sisu/tools/ldapsearch/LDAPsearchSISU.php
        statusCheck: false
        id: 0_1631_ldap
      - title: Ivanti
        icon: ''
        url: >-
          https://servicedesk.uclouvain.be/ServiceDesk.WebAccess/wd/query/list.rails?class_name=IncidentManagement.Incident&query=_IncidentsouvertsFirstetSD
        statusCheck: false
        id: 1_1631_ivanti
      - title: Confluence
        url: https://uclouvain.atlassian.net/wiki/spaces/SD/overview
        statusCheck: false
        id: 2_1631_confluence
      - title: MS Console
        url: http://msconsole.siws.ucl.ac.be/
        statusCheck: false
        id: 3_1631_msconsole
      - title: Password reset
        url: https://sites.uclouvain.be/sisu/tools/rstpwd/
        statusCheck: false
        id: 4_1631_passwordreset
      - title: Jira
        url: https://uclouvain.atlassian.net/jira/dashboards/10025
        statusCheck: false
        id: 5_1631_jira
      - title: Gestion accès externes
        url: >-
          https://sites.uclouvain.be/sgsi-apps/shib-accesressources/prod/index.php
        statusCheck: false
        id: 6_1631_gestionaccsexternes
