apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oauth
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAQxjq7n5oAgs5/LFxbbRJ7yp2iHKKVeTVRGyaqkyP2fPClaIpHsw4o44lYz5oM5qK563jEsb5CsEiSZknOMgqwglSIKtu5YiBqhfeSNKF6D88lWIBZ6OVHLqbDejOTUX18wijBQwpnYtAxZDc4H6w8mwFDmuo6Z2OXcZ47mZPV8mI8RLa6UJFGcAYQCb5g8QrlHox7HmQReBBO1PI9kkmvX9HTsL0Cq76FcAcFe1MGUcsjMyPU/y1HKIGw3njkOMLz2i+Zk7Mp1y0zIMEELuzfs7A9oQzEoMWezsjYkyhCFb5MNCfHwNeY5bDlOt6eNFpZySCDXNshiZSPPPX40SLXwdE2O6NPR09Oe211Tp3EwVZraFQJFhecW0j+dA7yMpwjZo/REwuRkAXZANETeXT0hZy+FSeTZ987kbZMcEyL+i2Qp+KXsppeLNoJcqJYkanvpLue4ZuPDU6QHl0K421lj7cW6V/boA+dcJEfnWIdzkGoCv+lrA8qaY1NHXCAJO8o+dSJ8oxLCQMib7yR9DzlUQ5dV49rPEZ8BceuW8CoCKhdIu3TfuuIzpkGBjgZx3Sy0kQn7oxhGgtStu0nummx/plo0K+svt8FE3kNI+jtcfN0l44eRMeaFvuhvdjwdlYZ1YSV8jCZ2oF0B3bUSXKzSl65h8oPhwNlrAoOv6LC32qvLtX8HYkgoEOYTZzwWSpNxO1oGuzJo2wFNGwMWqTnFh3JVAN3rWao4/yOh9c/CkqDGgOMv+0jkrfgzhNt2JPUY3WRF0iLBcAiwmqz46vX
    GF_DATABASE_PASSWORD: AgCACDiXkzY9HufTgaL+PSzWPxfhghA7BHGZJ468JCqskEBeUfC/OputE4Su5HQmbcwT9eC1OjahJaAsVuA48dK4lXHrEg/rynUi8qdjoACryZQ1z2p9hpyRiDeWtl9nG2dg1h1j6+K47xoYdfxqiYNWlH2rCUhEOFgCDvhslv/bGxJd505ekkAWA0C2YgHO5Nf8uB6h5Ojsb/rWoPQdD0EtgUaO+0q6JskyJfwivV+tx8qAuWPNJtGXEn5n7n+ZyL6x313B0TGWbiJeZIdemKnDCwK6+A2oOBq71GFoXXypO6JNgD05xyDxNP+KsU+JZalatWTszVDSACD/rFwGjlcBgh2w6F0ksr6BQY166st1kMrw577HbiqnrWJzSeygY32sqD3Vxb4Nc7+HvU6tkh/msBwIVGTLvvlT6NXVB6sGrviW5cuvwEbENqnDSfB8scetocHqelh82sryzXVasG+wZF4tzk1+/E364lLeIUNDxA+UASkLxPVXJrKCBianF+vYEUXyTJB+RGQorb6YZO5GaYXPvqiSw8vUx857bIsW7pLomrHPvbn2MVsN7GxXNNroHdL5pOUFoqDMP4Ilr5jY8tOcKu6eq2F4fZoprJyyGVWTGPH6xYd7XvDnDlDWHVAQYamgqCku4rd9jedcbLBdTHpDmUVU/LsG/lAwifxIj43+g+5If5WrId/VeGCmCvHkdfhy3niqBo8SjTDxGeuOeHMuweS8z7rtNSrljtacPVyScc1XdrpJxR3UNI9YDrlG29Qy6yBQf3vRqB4592Hb
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-oauth
      namespace: monitoring
    type: Opaque

