apiVersion: v1
kind: ConfigMap
metadata:
  name: wikijs
  namespace: wiki
data:
  DB_TYPE: postgres
  DB_HOST: postgres.storage.svc.cluster.local
  DB_PORT: "5432"
  DB_USER: wikijs
  DB_NAME: wikijs
  HA_ACTIVE: "true"
  NODE_EXTRA_CA_CERTS: "/certs/bhasherCA.pem"